#!/bin/bash

{
  echo "APP_NAME=$APP_NAME"
  echo "MAIN_SUPERUSER=$MAIN_SUPERUSER"
  echo "MAIN_SUPERUSER_PASSWORD=$MAIN_SUPERUSER_PASSWORD"
  echo "POSTGRES_SERVER=$POSTGRES_SERVER"
  echo "POSTGRES_PORT=$POSTGRES_PORT"
  echo "POSTGRES_USER=$POSTGRES_USER"
  echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
  echo "POSTGRES_DB=$POSTGRES_DB"
  echo "DATABASE_URI=$DATABASE_URI"
  echo "JWT_ALGORITHM=$JWT_ALGORITHM"
  echo "JWT_SECRET=$JWT_SECRET"
} >> .env

{
  echo "POSTGRES_DB=$POSTGRES_DB"
  echo "POSTGRES_USER=$POSTGRES_USER"
  echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
} >> .env.db
