version: "3.9"

services:
  db:
    image: postgres:13-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5777:5432"
    env_file:
      - ./.env.db
    networks:
      - api
  pgadmin4:
    image: "dpage/pgadmin4:latest"
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - ./.env.db.admin
    networks:
      - api
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/api/
    depends_on:
      - db
    networks:
      - api

networks:
    api:
        driver: bridge

volumes:
  postgres_data:

